### ISSUE TITLE
Bot replying to very old mentions

### ISSUE THREAD

**Issue by sevgrey** [grindcrank/twitter_ebooks#5]
Hello! 

I'm very much not a programmer so feel free to close this if this is something that isn't really possible but, since switching to twitter_ebooks_poll, my bot has been mass-replying to things several months old, in somewhat chronological order. Looking at the logs, it is flagging certain things as duplicates and as such not firing the event, but seems to then go ahead and reply anyways. Would it be possible to allow limiting of date-ranges for replies?

**Comment by grindcrank** [comment]
I still have to update the README - the last mention and the last home timeline tweet IDs are persisted in a simple JSON file. Since at first start you do not have any persisted "last info", the script will happily load the maximum of available mentions.

The idea with the date ranges is a good one - I will consider that for the next release. In my spare time. Which is very limited at the moment ;-(

**Comment by simonszu** [comment]
I want to add a phenomenon to this issue what i have experienced with my bot. It has the same behavior like @sevgrey s bot, but it happens that it doesnt reply to any mention before that at all. So i cannot confirm if the bot is just mass-replying to all the mentions it got before a restart, or that it is mass-replying because of this issue.

**Comment by grindcrank** [comment]
This finding is correct - when the bot starts up without any persisted "last tweet/mention id", it first replies to all mentions. I will take a look into that.

**Comment by grindcrank** [comment]
The Twitter API does not support date ranges - see https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-home_timeline.html

**Comment by grindcrank** [comment]
Fixed in 3.2.2.
